apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: adh-exploit-open-redirect
  name: adh-exploit-open-redirect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adh-exploit-open-redirect
  template:
    metadata:
      labels:
        app: adh-exploit-open-redirect
    spec:
      containers:
        - name: adh-exploit-open-redirect
          image: adiffhunting/exploit-open-redirect:493e0b3
          env:
            - name: DEBUG
              value: "true"
            - name: DGRAPH_ALPHA_HOST
              value: "dgraph-alpha.adh-db"
            - name: DGRAPH_ALPHA_HTTP_PORT
              value: "8080"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 256Mi
