version: "3.8"
services:

  dgraph-zero:
    image: dgraph/dgraph:v23.1.0
    command: dgraph zero --my=dgraph-zero:5080
    expose:
      - "5080"
      - "6080"
    volumes:
      - db-data:/dgraph
    restart: unless-stopped

  dgraph-alpha:
    image: dgraph/dgraph:v23.1.0
    command: dgraph alpha --my=dgraph-alpha:7080 --zero=dgraph-zero:5080 --security whitelist=0.0.0.0/0
    ports:
      - 8080:8080
    volumes:
      - db-data:/dgraph
    restart: on-failure

  dgraph-ratel:
    image: dgraph/ratel:v21.12.0
    ports:
      - 8000:8000
    restart: unless-stopped

  dgraph-init:
    build:
      dockerfile: db/dgraph-init/Dockerfile
      context: . # dev dir (needed to copy _utils)
    environment:
      - DEBUG=$DEBUG
      - DGRAPH_ALPHA_HOST=dgraph-alpha
      - DGRAPH_ALPHA_HTTP_PORT=8080
    volumes:
      - ./db/dgraph-init/test_data:/src/data

  subenum-passive:
    build:
      dockerfile: recon/subenum-passive/Dockerfile
      context: . # dev dir (needed to copy _utils)
    environment:
      - DEBUG=$DEBUG
      - DGRAPH_ALPHA_HOST=dgraph-alpha
      - DGRAPH_ALPHA_HTTP_PORT=8080
      - CHAOS_KEY=$CHAOS_KEY

  subprobe-dns:
    build:
      dockerfile: recon/subprobe-dns/Dockerfile
      context: . # dev dir (needed to copy _utils)
    environment:
      - DEBUG=$DEBUG
      - DGRAPH_ALPHA_HOST=dgraph-alpha
      - DGRAPH_ALPHA_HTTP_PORT=8080

  subtko:
    build:
      dockerfile: exploit/subtko/Dockerfile
      context: . # dev dir (needed to copy _utils)
    environment:
      - DEBUG=$DEBUG
      - DGRAPH_ALPHA_HOST=dgraph-alpha
      - DGRAPH_ALPHA_HTTP_PORT=8080
      - DOMAIN_SCAN_COOLDOWN=30 seconds

  xss:
    build:
      dockerfile: exploit/xss/Dockerfile
      context: . # dev dir (needed to copy _utils)
    environment:
      - DEBUG=$DEBUG
      - DGRAPH_ALPHA_HOST=dgraph-alpha
      - DGRAPH_ALPHA_HTTP_PORT=8080
      - DOMAIN_SCAN_COOLDOWN=30 seconds

  rce:
    build:
      dockerfile: exploit/rce/Dockerfile
      context: . # dev dir (needed to copy _utils)
    environment:
      - DEBUG=$DEBUG
      - DGRAPH_ALPHA_HOST=dgraph-alpha
      - DGRAPH_ALPHA_HTTP_PORT=8080
      - DOMAIN_SCAN_COOLDOWN=30 seconds

  sqli:
    build:
      dockerfile: exploit/sqli/Dockerfile
      context: . # dev dir (needed to copy _utils)
    environment:
      - DEBUG=$DEBUG
      - DGRAPH_ALPHA_HOST=dgraph-alpha
      - DGRAPH_ALPHA_HTTP_PORT=8080
      - DOMAIN_SCAN_COOLDOWN=30 seconds

  lfi:
    build:
      dockerfile: exploit/lfi/Dockerfile
      context: . # dev dir (needed to copy _utils)
    environment:
      - DEBUG=$DEBUG
      - DGRAPH_ALPHA_HOST=dgraph-alpha
      - DGRAPH_ALPHA_HTTP_PORT=8080
      - DOMAIN_SCAN_COOLDOWN=30 seconds

  ssrf:
    build:
      dockerfile: exploit/ssrf/Dockerfile
      context: . # dev dir (needed to copy _utils)
    environment:
      - DEBUG=$DEBUG
      - DGRAPH_ALPHA_HOST=dgraph-alpha
      - DGRAPH_ALPHA_HTTP_PORT=8080
      - DOMAIN_SCAN_COOLDOWN=30 seconds

volumes:
  db-data: {}
