apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: adh-recon-subprobe-dns
  name: adh-recon-subprobe-dns
spec:
  replicas: 0
  selector:
    matchLabels:
      app: adh-recon-subprobe-dns
  template:
    metadata:
      labels:
        app: adh-recon-subprobe-dns
    spec:
      containers:
        - name: adh-recon-subprobe-dns
          image: adiffhunting/recon-subprobe-dns:0350978
          env:
            - name: DEBUG
              value: "true"
            - name: DGRAPH_ALPHA_HOST
              value: "dgraph-alpha.adh-db"
            - name: DGRAPH_ALPHA_HTTP_PORT
              value: "8080"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 128Mi
