apiVersion: batch/v1
kind: Job
metadata:
  generateName: adh-db-dgraph-init
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 10
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: adh-db-dgraph-init
          image: adiffhunting/db-dgraph-init:a79eae8
          env:
            - name: DEBUG
              value: "false"
            - name: DGRAPH_ALPHA_HOST
              value: "dgraph-alpha.adh-db"
            - name: DGRAPH_ALPHA_HTTP_PORT
              value: "8080"
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 32Mi
          volumeMounts:
            - name: adh-db-dgraph-init-data
              mountPath: /src/data
              readOnly: true
      volumes:
        - name: adh-db-dgraph-init-data
          secret:
            secretName: adh-db-dgraph-init-data
