apiVersion: batch/v1
kind: Job
metadata:
  name: adh-db-dgraph-init
  namespace: adh
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 10
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: adh-db-dgraph-init
          image: adiffhunting/db-dgraph-init:3d3fe08
          env:
            - name: DEBUG
              value: "false"
            - name: DGRAPH_ALPHA_HOST
              value: "dgraph-alpha"
            - name: DGRAPH_ALPHA_HTTP_PORT
              value: "8080"
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 32Mi
