apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: adh-exploit-subtko
  name: adh-exploit-subtko
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adh-exploit-subtko
  strategy:
   type: Recreate
  template:
    metadata:
      labels:
        app: adh-exploit-subtko
    spec:
      containers:
        - name: adh-exploit-subtko
          image: adiffhunting/exploit-subtko:18b8ce7
          env:
            - name: DEBUG
              value: "true"
            - name: DGRAPH_ALPHA_HOST
              value: "dgraph-alpha"
            - name: DGRAPH_ALPHA_HTTP_PORT
              value: "8080"
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              memory: 256Mi
