apiVersion: v1
kind: Service
metadata:
  name: adh-database-nodeport
spec:
  type: NodePort
  selector:
    cnpg.io/cluster: adh-database
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      nodePort: 30001
