.: &default
  project: default
  autoSync:
    enabled: true
    prune: true
    selfHeal: true
  destination: &defaultDestination
    server: https://kubernetes.default.svc

.: &defaultRepoURL https://github.com/adiffpirate/adiffhunting
.: &defaultTargetRevision master

.: &sopsPlugin plain-and-encrypted-yaml-files
.: &dbNamespace db
.: &reconNamespace recon
.: &exploitNamespace exploit

applications:

  db:
    sources:
      - repoURL: https://charts.dgraph.io
        chart: dgraph
        targetRevision: 0.3.0
        helm:
          valueFiles:
            - $adiffhunting/ops/live/db/dgraph/values.yaml
      - repoURL: *defaultRepoURL
        targetRevision: *defaultTargetRevision
        path: ops/live/db
        plugin:
          name: *sopsPlugin
        ref: adiffhunting
    <<: *default
    destination:
      <<: *defaultDestination
      namespace: db

  prometheus-stack:
    sources:
      - repoURL: https://prometheus-community.github.io/helm-charts
        chart: kube-prometheus-stack
        targetRevision: 56.6.2
        helm:
          valueFiles:
            - $adiffhunting/ops/live/observability/prometheus-stack/values.yaml
      - repoURL: *defaultRepoURL
        targetRevision: *defaultTargetRevision
        path: ops/live/observability/prometheus-stack
        plugin:
          name: *sopsPlugin
        ref: adiffhunting
    <<: *default
    destination:
      <<: *defaultDestination
      namespace: observability

  loki-stack:
    sources:
      - repoURL: https://grafana.github.io/helm-charts
        chart: loki-stack
        targetRevision: 2.10.1
        helm:
          valueFiles:
            - $adiffhunting/ops/live/observability/loki-stack/values.yaml
      - repoURL: *defaultRepoURL
        targetRevision: *defaultTargetRevision
        path: ops/live/observability/loki-stack
        plugin:
          name: *sopsPlugin
        ref: adiffhunting
    <<: *default
    destination:
      <<: *defaultDestination
      namespace: observability

  alert:
    sources:
      - repoURL: *defaultRepoURL
        targetRevision: *defaultTargetRevision
        path: ops/live/alert
        plugin:
          name: *sopsPlugin
    <<: *default
    destination:
      <<: *defaultDestination
      namespace: alert

  recon:
    sources:
      - repoURL: *defaultRepoURL
        targetRevision: *defaultTargetRevision
        path: ops/live/recon
        plugin:
          name: *sopsPlugin
    <<: *default
    destination:
      <<: *defaultDestination
      namespace: recon

  exploit:
    sources:
      - repoURL: *defaultRepoURL
        targetRevision: *defaultTargetRevision
        path: ops/live/exploit
        plugin:
          name: *sopsPlugin
    <<: *default
    destination:
      <<: *defaultDestination
      namespace: exploit
