.: &default
  project: default
  autoSync: &defaultAutoSync
    enabled: true
    prune: true
    selfHeal: true
    onlyOutOfSync: true
    serverSideApply: false
  destination: &defaultDestination
    server: https://kubernetes.default.svc

.: &defaultRepoURL https://github.com/adiffpirate/adiffhunting
.: &defaultTargetRevision master

.: &sopsPlugin plain-and-encrypted-yaml-files
.: &dbNamespace db
.: &reconNamespace recon
.: &exploitNamespace exploit

applications:

  db:
    sources:
      - repoURL: https://charts.dgraph.io
        chart: dgraph
        targetRevision: 0.3.0
        helm:
          valueFiles:
            - $adiffhunting/ops/live/db/dgraph/values.yaml
      - repoURL: *defaultRepoURL
        targetRevision: *defaultTargetRevision
        path: ops/live/db
        plugin:
          name: *sopsPlugin
        ref: adiffhunting
    <<: *default
    destination:
      <<: *defaultDestination
      namespace: db

  prometheus-stack:
    sources:
      - repoURL: https://prometheus-community.github.io/helm-charts
        chart: kube-prometheus-stack
        targetRevision: 56.6.2
        helm:
          valueFiles:
            - $adiffhunting/ops/live/observability/prometheus-stack/values.yaml
      - repoURL: *defaultRepoURL
        targetRevision: *defaultTargetRevision
        path: ops/live/observability/prometheus-stack
        plugin:
          name: *sopsPlugin
        ref: adiffhunting
    <<: *default
    autoSync:
      <<: *defaultAutoSync
      serverSideApply: true
    destination:
      <<: *defaultDestination
      namespace: observability

  promtail:
    sources:
      - repoURL: https://grafana.github.io/helm-charts
        chart: promtail
        targetRevision: 6.15.5
        helm:
          valueFiles:
            - $adiffhunting/ops/live/observability/promtail/values.yaml
      - repoURL: *defaultRepoURL
        targetRevision: *defaultTargetRevision
        path: ops/live/observability/promtail
        plugin:
          name: *sopsPlugin
        ref: adiffhunting
    <<: *default
    destination:
      <<: *defaultDestination
      namespace: observability

  loki:
    sources:
      - repoURL: https://grafana.github.io/helm-charts
        chart: loki
        targetRevision: 5.43.1
        helm:
          valueFiles:
            - $adiffhunting/ops/live/observability/loki/values.yaml
      - repoURL: *defaultRepoURL
        targetRevision: *defaultTargetRevision
        path: ops/live/observability/loki
        plugin:
          name: *sopsPlugin
        ref: adiffhunting
    <<: *default
    autoSync:
      <<: *defaultAutoSync
      serverSideApply: true
    destination:
      <<: *defaultDestination
      namespace: observability

  alert:
    sources:
      - repoURL: *defaultRepoURL
        targetRevision: *defaultTargetRevision
        path: ops/live/alert
        plugin:
          name: *sopsPlugin
    <<: *default
    destination:
      <<: *defaultDestination
      namespace: alert

  recon:
    sources:
      - repoURL: *defaultRepoURL
        targetRevision: *defaultTargetRevision
        path: ops/live/recon
        plugin:
          name: *sopsPlugin
    <<: *default
    destination:
      <<: *defaultDestination
      namespace: recon

  exploit:
    sources:
      - repoURL: *defaultRepoURL
        targetRevision: *defaultTargetRevision
        path: ops/live/exploit
        plugin:
          name: *sopsPlugin
    <<: *default
    destination:
      <<: *defaultDestination
      namespace: exploit
