apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: adh-recon-subenum-passive
  name: adh-recon-subenum-passive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adh-recon-subenum-passive
  template:
    metadata:
      labels:
        app: adh-recon-subenum-passive
    spec:
      containers:
        - name: adh-recon-subenum-passive
          image: adiffhunting/recon-subenum-passive:1aa93f7
          env:
            - name: DEBUG
              value: "true"
            - name: DGRAPH_ALPHA_HOST
              value: "dgraph-alpha"
            - name: DGRAPH_ALPHA_HTTP_PORT
              value: "8080"
            - name: CHAOS_KEY
              valueFrom:
                secretKeyRef:
                  name: adh-recon-subenum-passive
                  key: chaos-api-key
          resources:
            requests:
              cpu: 250m
              memory: 64Mi
            limits:
              memory: 64Mi
