{{- range $key,$val := .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $val.project }}
  sources:
    {{- toYaml $val.sources | nindent 4 }}
  destination:
    namespace: {{ $val.destination.namespace }}
    server: {{ $val.destination.server }}
  {{- if $val.autoSync.enabled }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly={{ $val.autoSync.onlyOutOfSync }}
      - ServerSideApply={{ $val.autoSync.serverSideApply }}
    automated:
      selfHeal: {{ $val.autoSync.selfHeal }}
      prune: {{ $val.autoSync.prune }}
  {{- end }}
{{- end }}
