apiVersion: batch/v1
kind: Job
metadata:
  name: adh-db-init
  namespace: adh
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 10
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: adh-db-init
          image: adiffhunting/db-init:f0c9ece
          env:
            - name: DEBUG
              value: "false"
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: adh-database-app
                  key: uri
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 128Mi
