apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: adh-exploit-xss
  name: adh-exploit-xss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adh-exploit-xss
  template:
    metadata:
      labels:
        app: adh-exploit-xss
    spec:
      containers:
        - name: adh-exploit-xss
          image: adiffhunting/exploit-xss:ef0bc40
          env:
            - name: DEBUG
              value: "true"
            - name: DGRAPH_ALPHA_HOST
              value: "dgraph-alpha.adh-db"
            - name: DGRAPH_ALPHA_HTTP_PORT
              value: "8080"
          resources:
            requests:
              cpu: 50m
              memory: 512Mi
            limits:
              memory: 512Mi
