apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xss
  name: xss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xss
  template:
    metadata:
      labels:
        app: xss
    spec:
      containers:
        - name: xss
          image: adiffhunting/exploit-xss:82479f4
          env:
            - name: DEBUG
              value: "false"
            - name: DGRAPH_ALPHA_HOST
              value: "dgraph-alpha.db"
            - name: DGRAPH_ALPHA_HTTP_PORT
              value: "8080"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 128Mi
