apiVersion: batch/v1
kind: CronJob
metadata:
  name: adh-recon-rootenum
spec:
  schedule: "0 */2 * * *"  # Runs every two hours at minute 0
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: adh-recon-rootenum
        spec:
          restartPolicy: Never
          concurrencyPolicy: Forbid
          containers:
            - name: adh-recon-rootenum
              image: adiffhunting/recon-rootenum:80889a8
              env:
                - name: DEBUG
                  value: "true"
                - name: DGRAPH_ALPHA_HOST
                  value: "dgraph-alpha"
                - name: DGRAPH_ALPHA_HTTP_PORT
                  value: "8080"
                - name: HACKERONE_USER
                  valueFrom:
                    secretKeyRef:
                      name: adh-recon-rootenum
                      key: hackerone-user
                - name: HACKERONE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: adh-recon-rootenum
                      key: hackerone-token
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
                limits:
                  memory: 128Mi
