apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: adh-exploit-rce
  name: adh-exploit-rce
spec:
  replicas: 0
  selector:
    matchLabels:
      app: adh-exploit-rce
  template:
    metadata:
      labels:
        app: adh-exploit-rce
    spec:
      containers:
        - name: adh-exploit-rce
          image: adiffhunting/exploit-rce:c0ef46c
          env:
            - name: DEBUG
              value: "true"
            - name: DGRAPH_ALPHA_HOST
              value: "dgraph-alpha.adh-db"
            - name: DGRAPH_ALPHA_HTTP_PORT
              value: "8080"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 128Mi
