apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: subprobe-dns
  name: subprobe-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subprobe-dns
  template:
    metadata:
      labels:
        app: subprobe-dns
    spec:
      containers:
        - name: subprobe-dns
          image: adiffhunting/recon-subprobe-dns:bba8868
          env:
            - name: DEBUG
              value: "false"
            - name: DGRAPH_ALPHA_HOST
              value: "dgraph-alpha.db"
            - name: DGRAPH_ALPHA_HTTP_PORT
              value: "8080"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 128Mi
