fullnameOverride: dgraph

zero:
  replicaCount: 1
  persistence:
    size: 3Gi

alpha:
  replicaCount: 1
  service:
    type: NodePort
  persistence:
    size: 10Gi
  extraFlags: "--security whitelist=0.0.0.0/0"
