fullnameOverride: dgraph

zero:
  replicaCount: 1
  persistence:
    size: 3Gi
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      memory: 200Mi

alpha:
  replicaCount: 1
  service:
    type: NodePort
  persistence:
    size: 10Gi
  extraFlags: -v=2 --security whitelist=0.0.0.0/0
  resources:
    requests:
      cpu: 300m
      memory: 12Gi
    limits:
      memory: 12Gi
  startupProbe:
    enabled: true
