fullnameOverride: dgraph

zero:
  replicaCount: 3
  persistence:
    size: 3Gi
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 128Mi

alpha:
  replicaCount: 3
  service:
    type: NodePort
  persistence:
    size: 10Gi
  extraFlags: -v=2 --security whitelist=0.0.0.0/0
  resources:
    requests:
      cpu: 150m
      memory: 2Gi
    limits:
      memory: 2Gi
  startupProbe:
    enabled: true
