name: Delivery

on:
  push:
    branches: ["master"]
    paths: ["dev/**"]

jobs:

  #-----------------------------------#
  # DEV: Build and push docker images #
  #-----------------------------------#

  docker-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        application: [
          "dgraph-init",
          "subenum-passive",
          "subprobe"
        ]
    
    steps:
      - uses: actions/checkout@v3
        name: Checkout source code
      
      - uses: docker/setup-qemu-action@v2
        name: Set up QEMU

      - uses: docker/setup-buildx-action@v2
        name: Set up Docker Buildx

      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get tag as commit hash
        id: vars
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: dorny/paths-filter@v2
        name: Get changed dirs
        id: filter
        with:
          filters: |
            utils:
              - dev/_utils/**
            app: 
              - dev/${{ matrix.application }}/**

      # Build and push image only if _utils or app dir has changed
      - uses: docker/build-push-action@v4
        name: Build
        if: ${{ (steps.filter.outputs.utils == 'true') || (steps.filter.outputs.app == 'true') }}
        with:
          file: dev/${{ matrix.application }}/Dockerfile
          context: dev
          push: true
          tags: adiffhunting/${{ matrix.application }}:${{ steps.vars.outputs.tag }}

  #-----------------------------------#
  # OPS: Update live environment code #
  #-----------------------------------#

  update-live:
    runs-on: ubuntu-latest
    needs: docker-push

    strategy:
      matrix:
        application: [
          "dgraph-init",
          "subenum-passive",
          "subprobe"
        ]

    steps:
      - uses: actions/checkout@v3
        name: Checkout source code

      - name: Get tag as commit hash
        id: vars
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: dorny/paths-filter@v2
        name: Get changed dirs
        id: filter
        with:
          filters: |
            utils:
              - dev/_utils/**
            app: 
              - dev/${{ matrix.application }}/**
      
      # Update image tag only if _utils or app dir has changed
      - name: Update deployment tag
        if: ${{ (steps.filter.outputs.utils == 'true') || (steps.filter.outputs.app == 'true') }}
        working-directory: ops/live
        env:
          APP: ${{ matrix.application }}
          TAG: ${{ steps.vars.outputs.tag }}
        run: |
          find . -name '*.yaml' -type f -exec sed -i "s/image: adiffhunting\/$APP\:.*$/image\: adiffhunting\/$APP\:$TAG/g" {} \;

      # Commit and push only if _utils or app dir has changed
      - uses: nick-fields/retry@v2
        name: Commit and push changes
        if: ${{ (steps.filter.outputs.utils == 'true') || (steps.filter.outputs.app == 'true') }}
        env:
          APP: ${{ matrix.application }}
          TAG: ${{ steps.vars.outputs.tag }}
        with:
          max_attempts: 10
          retry_on: error
          timeout_seconds: 5
          command: |
            git config --global user.name "GitHub Action"
            git config --global user.email "action@github.com"
            git stash
            git pull
            git stash pop
            git add -A
            git commit -m "{ops}[$APP] Bump image tag to $TAG"
            git push
