loki:
  enabled: true

  global:
    priorityClassName: system-cluster-critical

  loki:
    storage:
      type: s3
      bucketNames:
        chunks: chunks
        ruler: ruler
        admin: admin
    commonConfig:
      replication_factor: 1

  backend:
    replicas: 1
    persistence:
      size: 10Gi
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 512Mi
    # affinity: |
    #   podAntiAffinity:
    #     preferredDuringSchedulingIgnoredDuringExecution:
    #       - weight: 100
    #         podAffinityTerm:
    #           labelSelector:
    #             matchLabels:
    #               {{- include "loki.backendSelectorLabels" . | nindent 12 }}
    #           topologyKey: topology.kubernetes.io/zone

  write:
    replicas: 1
    persistence:
      size: 10Gi
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 512Mi
    # affinity: |
    #   podAntiAffinity:
    #     preferredDuringSchedulingIgnoredDuringExecution:
    #       - weight: 100
    #         podAffinityTerm:
    #           labelSelector:
    #             matchLabels:
    #               {{- include "loki.writeSelectorLabels" . | nindent 12 }}
    #           topologyKey: topology.kubernetes.io/zone

  read:
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 10
    resources:
      limits:
        cpu: 100m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 512Mi
    # affinity: |
    #   podAntiAffinity:
    #     preferredDuringSchedulingIgnoredDuringExecution:
    #       - weight: 100
    #         podAffinityTerm:
    #           labelSelector:
    #             matchLabels:
    #               {{- include "loki.readSelectorLabels" . | nindent 12 }}
    #           topologyKey: topology.kubernetes.io/zone

  monitoring:
    serviceMonitor:
      enabled: true
      labels:
        release: prometheus-stack
    lokiCanary:
      # Schedule on all nodes with high priority
      priorityClassName: system-node-critical
      tolerations:
        - operator: Exists
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi

  minio:
    enabled: true
    persistence:
        size: 10Gi


promtail:
  enabled: true

  # Schedule on all nodes with high priority
  priorityClassName: system-node-critical
  tolerations:
    - operator: Exists

  # https://github.com/grafana/loki/issues/7081#issuecomment-1239386350
  config:
    clients:
      - url: http://loki-stack-gateway/loki/api/v1/push
        tenant_id: logs

  resources:
    limits:
      cpu: 125m
      memory: 256Mi
    requests:
      cpu: 125m
      memory: 256Mi

  serviceMonitor:
    enabled: true
    labels:
      release: prometheus-stack


fluent-bit:
  enabled: false


prometheus:
  enabled: false


filebeat:
  enabled: false


logstash:
  enabled: false
